name: Publish Package

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-publish-package:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:Threshold=81
    - name: Generate Release
      run: dotnet publish
    - name: Pack
      run: dotnet pack
    - name: Add nuget source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/lorenzonicolas/index.json"
    - name: Publish package
      run: dotnet nuget push "./nll-file-system-utils/bin/Release/*.nupkg" --source "github"
